version: '3.8'

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: skoolu
			POSTGRES_PASSWORD: XSW@xsw2
			POSTGRES_DB: school
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: skoolu
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://skoolu:XSW@xsw2@[0.0.0.0]:5432/mydb
    depends_on:
      - postgres

volumes:
  postgres_data: